### ISSUE TITLE
как форму наверх поднять?

### ISSUE THREAD

**Issue by real-mielofon** [bobuk/kittycheck#11]
на странице http://www.office.sprut.ru/wp/
при checkin на коте форма под картинку заходит.
Подскажите: как её наверх вытянуть?

**Comment by gornostal** [comment]
погодь секунду
поставлю больше z-index

**Comment by gornostal** [comment]
жми ctrl+f5
должно работать

**Comment by real-mielofon** [comment]
Спасибо. Сработало :-)
