### ISSUE TITLE
Баг в сафари

### ISSUE THREAD

**Issue by yakutin** [bobuk/kittycheck#19]
в `<head>` прописал коды

```
<script src="http://kittycheck.com/js/inject.js"></script>
<meta name="kittycheck_rumble" content="true" />
```

китечек отлично работает и мурлычет в хроме, опере и ie
в сафари не работает вообще!

если убрать мурлыканье (`<meta name="kittycheck_rumble" content="true" />`) в сафари работает нормально
помогите плз

**Comment by bobuk** [comment]
покажите на какой странице не мрулычет, чтобы найти ошибку?
Можно просто URL.

**Comment by yakutin** [comment]
yakutin.com
в сафари вообще ничего не работает

**Comment by bobuk** [comment]
У вас 

```
<script src="http://kittycheck.com/js/inject.js"></script>
<meta name="kittycheck_rumble" content="true" />
```

всё это у вас вставлено МЕЖДУ head и body. переместите на одну строку вверх, поставьте ПЕРЕД `</head>`

После этого нажмите обновить - всё заработает.

**Comment by yakutin** [comment]
Григорий, 
сделал как вы сказали, в сафари заработало, но не мурлычит :(
в хроме, опере и ie работает отлично

причем, в том же сафари котята на kittycheck.com и addmeto.cc мурлычат в голос

**Comment by yakutin** [comment]
Прошу прощения за флуд!
в сафари на винде все работает...
а на моем родном сафари 5.2 на macbook air не мурлычит :(
понимаю, что проблема на моей стороне, но ведь, блин, не работает... :(

**Comment by bobuk** [comment]
скорее всего сафари закешировал что-то неправильно.
достаточно просто сделать полный рефреш страницы.

**Comment by yakutin** [comment]
рефреш страницы - это первое, что я сделал 
старая виндовая привычка - если что-то не работает надо перезагрузить )))))

ладно, Григорий, закрываем issue
спасибо вам большое
