### ISSUE TITLE
Не приходит имя твиттер-юзера

### ISSUE THREAD

**Issue by gornostal** [bobuk/kittycheck#2]
В комментариях должно приходить

```
...
"author": {
      "name" : "author name",
      "login": "twitter login"
 },
...
```

а сейчас и в `name` и в `login` приходит `login`

похоже нужно делать доп. запрос на твиттер

**Comment by syndicut** [comment]
Если мы имя будем хранить в локальной базе это ок, как думаешь или тягать из твиттера каждый раз?

**Comment by gornostal** [comment]
конечно же не тягать каждый раз))
лучше в базе

ты можешь допилить?

**Comment by syndicut** [comment]
Ага

**Comment by syndicut** [comment]
Да, без доп. запроса в твиттер не обойтись, он в коллбеке возвращает только логин.

**Comment by gornostal** [comment]
ага, я тоже это увидел

**Comment by syndicut** [comment]
Запрос тащем-то простой, попробуем ща:
https://api.twitter.com/1/users/show.json?screen_name=bobuk&include_entities=false
