### ISSUE TITLE
Разный размер шрифта для анонимного и авторизованного пользователя в checkin-сообщении

### ISSUE THREAD

**Issue by syndicut** [bobuk/kittycheck#3]
Сделаем побольше на странице с комментами или уменьшим на странице с чекином? Может вынести в отдельный темплейт?

**Comment by gornostal** [comment]
мне и так нравится
хочешь - делай :)

**Comment by gornostal** [comment]
я бы уменьшил еще на 1px размер имени автора
как считаешь?

**Comment by syndicut** [comment]
Не, ну если это ок, до давай оставим

**Comment by syndicut** [comment]
Да, согласен
