### ISSUE TITLE
Сделать кошку урчащей

### ISSUE THREAD

**Issue by syndicut** [bobuk/kittycheck#5]
Так, идея в порядке бреда, по-моему слегка китчево, должно быть отключаемо.

**Comment by bobuk** [comment]
Ну так попробуй сделать, не? звуком прямо?

**Comment by syndicut** [comment]
Ага, ща попробую. Да, звуком.

**Comment by syndicut** [comment]
Звук конечно так себе, но кто хочет может поправить семпл, если найдет лучше.

**Comment by bobuk** [comment]
я так и не смог звук услышать. ни в ff, ни в safari

**Comment by syndicut** [comment]
Хммм, странно, у меня и в фф и в хроме играет. Завтра подебажу, может зависить от версии флеша, в принципе. Хотя где есть htmtl5 - она его должна использовать.

**Comment by syndicut** [comment]
А, не, он старается юзать флеш и только  когда флеша нет, пробует HTML5

**Comment by syndicut** [comment]
Проверил на ноуте с виндой - работает в IE8, Fx 11,0, Opera 9.6, Chrome latest stable

**Comment by syndicut** [comment]
Даже на хакинтоше с Safari 3.1 и Firefox 4 работает, так что ворксформи какой-то выходит.

**Comment by bobuk** [comment]
странно. а у меня не работает. Как проверять?

**Comment by bobuk** [comment]
посмотрел в логи, файл .mp3 ни у кого не запрашивается

**Comment by syndicut** [comment]
Подожди, а ты как проверяешь? Я тут:
http://kittycheck.com/demo.html

**Comment by syndicut** [comment]
Ну и для включения нужна мета:

``` html
<meta name="kittycheck_rumble" content="true" />
```

**Comment by bobuk** [comment]
1. не грузился скрипт в js, ты его по относительному урлу забирал. я вроде пофиксил как мог, см. последний камит.
2. сейчас не находит файл soundmanager2.swf, тоже пытается его грузить не с того хоста.

**Comment by syndicut** [comment]
Да, я понял, засада в относительных урлах, ша сделаем

**Comment by syndicut** [comment]
А где можно потестить не на этом же домене?

**Comment by syndicut** [comment]
Все, теперь должна быть победа

**Comment by bobuk** [comment]
http://addmeto.cc/
кстати, чтоб два раза не вставать  - обрати где там появляется окно коментариев

**Comment by syndicut** [comment]
Ох, щи, там мозговзрывательная логика позиционирования. Скажи лучше, где оно в идеале должно появляться?

**Comment by gornostal** [comment]
> обрати где там появляется окно коментариев

пофиксил

**Comment by syndicut** [comment]
Вот только линия на addmeto.cc из под киски видна, это ок?

**Comment by gornostal** [comment]
может потому что кошка прозрачная?:)

**Comment by syndicut** [comment]
Это я заметил, я просто думаю, может она предполагалась правее, где не пересекалась с линией =)

**Comment by bobuk** [comment]
Откатил на addmeto кошечку направо. Там она лучше смотрится.
И всё же, как вам новая картинка? Хочу ее менять иногда, девушка нарисовала с десяток, но они разного размера :(

**Comment by syndicut** [comment]
Я подумал что кошечка такая, потому что уже ночь, типа уснула :-D

**Comment by syndicut** [comment]
Предыдущая была схематичная, а это более, так сказать, фотореалистичнее. Они разные, трудно сравнить, хуже-лучше. Если будут в одном стиле - то здорово будет.

**Comment by bobuk** [comment]
![image1](https://img.skitch.com/20120528-b81ixmt5556x46wxe2qi8grqh.png)

![image2](https://img.skitch.com/20120528-1jqkw5g7pcu6g84sip6fsp2hfk.png)

**Comment by bobuk** [comment]
И по теме: у меня на addmeto.cc всё еще не урчит :(

29.05.2012, 01:06, "syndicut" reply@reply.github.com:

> Предыдущая была схематичная, а это более, так сказать, фотореалистичнее. Они разные, трудно сравнить, хуже-лучше. Если будут в одном стиле - то здорово будет.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bobuk/kittycheck/issues/5#issuecomment-5972080

## 

S.Y. BoBuk.
Absolutist

**Comment by syndicut** [comment]
А у нас с Сашей урчит вроде. Непонятно.

**Comment by syndicut** [comment]
Если сброс кешей непомогает - то не знаю. У тебя флешка грузится? А mp3?

**Comment by syndicut** [comment]
У меня вообще все сломалось на addmeto.cc, только кружок вертится

**Comment by syndicut** [comment]
Так, Я БОЛЬШЕ НИКОГДА НЕ БУДУ КОПИПАСТИТЬ КОД

**Comment by syndicut** [comment]
Окно с комментами кстати увело влево

**Comment by bobuk** [comment]
окно с каментами унесло в жопу. в хроме и сафари нормально, а в фаерфоксе - вниз окна :(

**Comment by bobuk** [comment]
Простите, я отреджектил последний коммит, а то окно уносило вообще в жопу :(

**Comment by syndicut** [comment]
Имхо, логику позиционирования надо переписать, я сломал в ней ногу, если честно.
