### ISSUE TITLE
Ну что, запускаем?

### ISSUE THREAD

**Issue by bobuk** [bobuk/kittycheck#6]
Мужики, @gornostal и @syndicut , посмотрите на главную страницу?
Поправьте что считаете нужным.
Я завтра буду про нее трубить :)

**Comment by gornostal** [comment]
а проблемы с позицией окна еще есть?

**Comment by syndicut** [comment]
Ну там Бобук вроде как откатил твои правки. Я запилил версию с тупым позицинированием, но оно умеет ставить окно с комментами только слева вверху, зато работает железобетонно, как по мне.

**Comment by bobuk** [comment]
в текущем виде баги только при position: relative у китечки

**Comment by gornostal** [comment]
Да, я тоже думал такое предложить

Просто у меня не получилось в некоторых случаях находить правильную позицию окна чтобы оно было возле кошки.

**Comment by syndicut** [comment]
Вот так я предлагаю, если ок - смерджите в мастер.

**Comment by syndicut** [comment]
Упс, забыл ксс кое-какой

**Comment by bobuk** [comment]
Слушай, ну даже мне надо бывает переместить кота
я его вообще хочу в случайное место на странице пихать. а ты такой жестокий! Давайте пока оставим как есть?

**Comment by gornostal** [comment]
думаю плохая идея относительного позиционирования окна
оно так нормально таскается?

**Comment by syndicut** [comment]
Нет, кот таскается через ксс как угодно, это окно с комментариями прибито гвоздями

**Comment by gornostal** [comment]
давай я посмотрю чуть позже как можно сделать
я когда последний раз правил, то не проверил во всех браузерах, а в хроме было все ОК

**Comment by syndicut** [comment]
И окно с комментами таскается ок у меня

**Comment by syndicut** [comment]
ну ок, тогда закроешь мой пулл реквест, если что

**Comment by bobuk** [comment]
Мужики, текст глазами прочитайте. И скажите можно ли анонсить наружу. Поправить баги вы успеете, сейчас есть ноун баг - плохо позишнит окно при position=relative, остальное вроде всё ок.

**Comment by syndicut** [comment]
А это кстати нормально, что кот перекрывает кольцо цекина? На красном кольце заметно, например.

**Comment by syndicut** [comment]
Да, я прочитал текст, мне все понравилось.

**Comment by gornostal** [comment]
мне тоже все нравится :)
анонсь

**Comment by syndicut** [comment]
Уточнил немного насчет мурлыканья и Flash

**Comment by bobuk** [comment]
Давно я не запускал розовых сайтов для девочек. Поехали в релиз.

**Comment by gornostal** [comment]
стой
сейчас фикс закину

**Comment by syndicut** [comment]
А это после твоих правок сломалась урчалка у кошки?

**Comment by gornostal** [comment]
у меня урчит на addmeto

**Comment by syndicut** [comment]
Да, поправилось. А вот расстояние такое от кошки до окна - это так и задумывалось?

**Comment by gornostal** [comment]
примерно 50px

**Comment by syndicut** [comment]
Тогда все круто, правда мне больше нравился отступ в 10, но это не суть.

**Comment by bobuk** [comment]
запустили пока
