### ISSUE TITLE
Поддержка touch девайсов

### ISSUE THREAD

**Issue by bobuk** [bobuk/kittycheck#9]
насколько я сходу вижу - коллбеки $(document).touchdown/up доступны.

**Comment by syndicut** [comment]
У меня даже каким-то волшебным способом получилось заставить кота поурчать с андроида.

**Comment by gornostal** [comment]
@syndicut есть опыт разработки под мобильные устройства?

**Comment by bobuk** [comment]
да не надо там особого опыта вроде. банально всё.

**Comment by gornostal** [comment]
попробую сейчас сделать

**Comment by gornostal** [comment]
уже работает на iPad

**Comment by il-krylov** [comment]
ага проверил, на ipad-e работает :)

**Comment by il-krylov** [comment]
@gornostal только бага смешная, можно чекиниться в любом месте страницы, а не только на котЭ

**Comment by syndicut** [comment]
На моем Андроиде тоже смешно глючит, сектор рисуется где-то не там, но в целом функционально и даже урчит.

**Comment by gornostal** [comment]
@shtirlizz да, действительно :) 
поправлю

**Comment by gornostal** [comment]
готово

**Comment by il-krylov** [comment]
@gornostal сейчас потестим ;)

**Comment by il-krylov** [comment]
@gornostal работает :)

**Comment by syndicut** [comment]
Да, отлично, теперь только сектор съезжает на андроиде, но это фиг с ним

**Comment by bobuk** [comment]
круто. работает!
